Repository NickRTR-Schule/Vokabeltrainer, pull requests merged in 2023-07, with the labels that each got.

#41 Feature/implement search
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/management/Kategorieliste.java
  src/benutzerschnittstelle/management/ListView.java
  src/benutzerschnittstelle/management/Vokabelliste.java
  src/fachkonzept/search/Suchkonzept.java
  src/fachkonzept/search/SuchkonzeptKategorie.java
  src/fachkonzept/search/SuchkonzeptVokabeln.java
Labels: help wanted, frontend, backend, feature

#42 Feature/vok kat mapping
  .classpath
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/libraries/junit_jupiter_api.xml
  .idea/misc 2.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations/Vokabeltrainer.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  Concept/Scrum/Daily Scrum.pdf
  Concept/Scrum/Product Backlog.xlsx
  Concept/Scrum/README.md
  Concept/Scrum/Sprint Burndown Chart.xlsx
  Concept/Scrum/Sprint Events.pdf
  Concept/Scrum/Sprint Retrospective.pdf
  Concept/outdated/Database/README.md
  Concept/outdated/Project/Logic.pdf
  Concept/outdated/UI/Dashboard.jpeg
  Concept/outdated/UI/Dashboard.jpg
  Concept/outdated/UI/Kategorieuebersicht.jpeg
  Concept/outdated/UI/README.md
  Concept/outdated/UI/Vokabelersteller.jpeg
  Concept/outdated/UI/Vokabelersteller.jpg
  Concept/outdated/UI/Vokabeltrainer Screens.fig
  Vokabeltrainer.iml
  src/benutzerschnittstelle/Abfrage.java
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/komponenten/CustomButton.java
  src/benutzerschnittstelle/komponenten/CustomPanel.java
  src/benutzerschnittstelle/komponenten/MappingWindow.java
  src/benutzerschnittstelle/komponenten/WrapperPanel.java
  src/benutzerschnittstelle/management/KategorieScreen.java
  src/benutzerschnittstelle/management/Kategorieliste.java
  src/benutzerschnittstelle/management/ListView.java
  src/benutzerschnittstelle/management/VokabelScreen.java
  src/benutzerschnittstelle/management/Vokabelliste.java
  src/benutzerschnittstelle/navigation/NavigationBar.java
  src/benutzerschnittstelle/navigation/UIScreens.java
  src/datenspeicherung/Datenbank.java
  src/datenspeicherung/Kategorie.java
  src/datenspeicherung/Vokabel.java
  src/fachkonzept/ErstellerKonzept.java
  src/fachkonzept/datamangement/tablemodels/CustomTableModel.java
  src/fachkonzept/datamangement/tablemodels/KategorieTableModel.java
  src/fachkonzept/datamangement/tablemodels/VokabelTableModel.java
  src/fachkonzept/navigation/NavigationStack.java
  src/steuerung/AbfrageSteuerung.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/MainFrameSteuerung.java
  src/steuerung/management/VokabelScreenSteuerung.java
Labels: frontend, backend, feature

#43 Refactor/database 1
  Tests/datenbank/DatenbankVokabelTest.java
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/komponenten/MappingWindow.java
  src/datenspeicherung/Datenbank.java
  src/datenspeicherung/Vokabel.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/MainFrameSteuerung.java
Labels: enhancement, backend

#44 Feature/abbildungen
  Resources/Icons/Image-placeholder.png
  Tests/datenbank/DatenbankVokabelTest.java
  src/benutzerschnittstelle/Abfrage.java
  src/benutzerschnittstelle/management/VokabelScreen.java
  src/benutzerschnittstelle/navigation/NavigationBar.java
  src/fachkonzept/datamangement/converting/CustomConverter.java
  src/fachkonzept/datamangement/tablemodels/KategorieTableModel.java
Labels: frontend, feature
