Repository NickRTR-Schule/Vokabeltrainer, pull requests merged in 2023-03, with the labels that each got.

#18 Feature/UI 1
  src/benutzerschnitstelle/Dashboard.java
  src/benutzerschnitstelle/GUI.java
  src/benutzerschnitstelle/MainFrame.java
  src/benutzerschnitstelle/UI.java
  src/datenspeicherung/Datenbank.java
  src/steuerung/MainFrameSteuerung.java
Labels: frontend, feature

#20 Feature/UI 3
  .classpath
  .gitignore
  .project
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.core.runtime.prefs
  .settings/org.eclipse.jdt.apt.core.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.launching.prefs
  .settings/org.eclipse.jdt.ui.prefs
  .settings/org.eclipse.ltk.core.refactoring.prefs
  Resources/Driver/ucanaccess/commons-lang-2.6.jar
  Resources/Driver/ucanaccess/commons-logging-1.1.1.jar
  Resources/Driver/ucanaccess/hsqldb.jar
  Resources/Driver/ucanaccess/jackcess-2.1.6.jar
  Resources/Driver/ucanaccess/ucanaccess-4.0.2.jar
  Resources/JUnit 5/apiguardian-api-1.1.2.jar
  Resources/JUnit 5/junit-jupiter-api-5.9.2.jar
  Resources/JUnit 5/junit-platform-commons-1.9.2.jar
  Resources/JUnit 5/opentest4j-1.2.0.jar
  Resources/JavaCodeStyleFormatterProfileLorenz.xml
  Tests/datenbank/DatenbankTest.java
  src/benutzerschnitstelle/Abfrage.java
  src/benutzerschnitstelle/Dashboard.java
  src/benutzerschnitstelle/ErrorScreen.java
  src/benutzerschnitstelle/Kategorieuebersicht.java
  src/benutzerschnitstelle/Konsole.java
  src/benutzerschnitstelle/MainFrame.java
  src/benutzerschnitstelle/Statistik.java
  src/benutzerschnitstelle/Vokabelersteller.java
  src/benutzerschnitstelle/komponenten/CustomButton.java
  src/benutzerschnitstelle/komponenten/KategorieTile.java
  src/benutzerschnitstelle/navigation/UIScreens.java
  src/datenspeicherung/Datenbank.java
  src/datenspeicherung/Kategorie.java
  src/datenspeicherung/Vokabel.java
  src/steuerung/AbfrageSteuerung.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/KategorieUebersichtsSteuerung.java
  src/steuerung/MainFrameSteuerung.java
  src/steuerung/StatistikSteuerung.java
  src/steuerung/VokabelerstellerSteuerung.java
  src/tests/DatenbankTest.java
Labels: frontend, project

#24 Feature/UI 4
  .settings/org.eclipse.jdt.core.prefs
  Tests/datenbank/DatenbankKategorieTest.java
  Tests/datenbank/DatenbankVokabelTest.java
  src/benutzerschnittstelle/Abfrage.java
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/ErrorScreen.java
  src/benutzerschnittstelle/Kategorieuebersicht.java
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/Statistik.java
  src/benutzerschnittstelle/Vokabelersteller.java
  src/benutzerschnittstelle/komponenten/CustomButton.java
  src/benutzerschnittstelle/komponenten/CustomPanel.java
  src/benutzerschnittstelle/komponenten/KategorieTile.java
  src/benutzerschnittstelle/komponenten/NavigationBar.java
  src/benutzerschnittstelle/komponenten/RoundedBorder.java
  src/benutzerschnittstelle/komponenten/StatistikPanel.java
  src/datenspeicherung/Datenbank.java
  src/datenspeicherung/Kategorie.java
  src/exceptions/EndOfAbfrageException.java
  src/exceptions/datenbank/DatenbankAccessException.java
  src/exceptions/datenbank/DatenbankAccessType.java
  src/exceptions/datenbank/DatenbankLeseException.java
  src/exceptions/datenbank/DatenbankObject.java
  src/exceptions/datenbank/DatenbankSchreibException.java
  src/exceptions/datenbank/DuplicateVokabelException.java
  src/steuerung/AbfrageSteuerung.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/KategorieUebersichtsSteuerung.java
  src/steuerung/MainFrameSteuerung.java
  src/steuerung/StatistikSteuerung.java
  src/steuerung/VokabelerstellerSteuerung.java
Labels: enhancement, frontend, backend, feature, project

#26 Feature/UI 5
  Resources/Icons/KategorieArrow.png
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/Vokabelersteller.java
  src/benutzerschnittstelle/komponenten/CustomPanel.java
  src/benutzerschnittstelle/komponenten/NavigationBar.java
Labels: frontend, backend

#27 Feature/backend 1
  .classpath
  Vokabeltrainer.accdb
  src/benutzerschnittstelle/Abfrage.java
  src/benutzerschnittstelle/Konsole.java
  src/datenspeicherung/Datenbank.java
  src/fachkonzept/AbfrageKonzept.java
  src/fachkonzept/ErstellerKonzept.java
  src/steuerung/AbfrageSteuerung.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/VokabelerstellerSteuerung.java
Labels: backend

#28 Feature/UI 6
  src/benutzerschnittstelle/Vokabelersteller.java
Labels: frontend
