Repository NickRTR-Schule/Vokabeltrainer, pull requests merged in 2023-04, with the labels that each got.

#29 Feature/abfrage UI 1
  src/benutzerschnittstelle/Abfrage.java
  src/datenspeicherung/Datenbank.java
  src/fachkonzept/AbfrageKonzept.java
  src/steuerung/AbfrageSteuerung.java
Labels: frontend, backend, feature

#32 Feature/UI 7
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/ErrorScreen.java
  src/benutzerschnittstelle/Konsole.java
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/Vokabelersteller.java
  src/benutzerschnittstelle/cli/Konsole.java
  src/benutzerschnittstelle/error/ErrorScreen.java
  src/benutzerschnittstelle/komponenten/NavigationBar.java
  src/benutzerschnittstelle/komponenten/Vokabeltile.java
  src/benutzerschnittstelle/navigation/UIScreens.java
  src/benutzerschnittstelle/uebersicht/Kategorieliste.java
  src/benutzerschnittstelle/uebersicht/Kategorieuebersicht.java
  src/benutzerschnittstelle/uebersicht/Vokabelliste.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/MainFrameSteuerung.java
  src/steuerung/uebersicht/KategorieUebersichtsSteuerung.java
  src/steuerung/uebersicht/KategorielisteSteuerung.java
  src/steuerung/uebersicht/VokabellisteSteuerung.java
Labels: frontend, feature

#33 Verwaltungslisten
  Concepts/UI/README.md
  Tests/datenbank/DatenbankVokabelTest.java
  src/benutzerschnittstelle/Abfrage.java
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/VokabelScreen.java
  src/benutzerschnittstelle/Vokabelersteller.java
  src/benutzerschnittstelle/komponenten/CustomButton.java
  src/benutzerschnittstelle/komponenten/KategorieTile.java
  src/benutzerschnittstelle/komponenten/NavigationBar.java
  src/benutzerschnittstelle/komponenten/Vokabeltile.java
  src/benutzerschnittstelle/uebersicht/Kategorieliste.java
  src/benutzerschnittstelle/uebersicht/Vokabelliste.java
  src/datenspeicherung/Datenbank.java
  src/datenspeicherung/Vokabel.java
  src/steuerung/DashboardSteuerung.java
  src/steuerung/MainFrameSteuerung.java
  src/steuerung/VokabelScreenSteuerung.java
  src/steuerung/VokabelerstellerSteuerung.java
  src/steuerung/uebersicht/KategorielisteSteuerung.java
  src/steuerung/uebersicht/VokabellisteSteuerung.java
Labels: frontend, backend, feature

#36 Update and improve UI
  Tests/datenbank/DatenbankKategorieTest.java
  src/benutzerschnittstelle/Abfrage.java
  src/benutzerschnittstelle/Dashboard.java
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/Statistik.java
  src/benutzerschnittstelle/cli/Konsole.java
  src/benutzerschnittstelle/error/ErrorScreen.java
  src/benutzerschnittstelle/komponenten/CustomPainter.java
  src/benutzerschnittstelle/komponenten/CustomPanel.java
  src/benutzerschnittstelle/komponenten/CustomTextField.java
  src/benutzerschnittstelle/komponenten/KategorieTile.java
  src/benutzerschnittstelle/komponenten/NavigationBar.java
  src/benutzerschnittstelle/komponenten/Vokabeltile.java
  src/benutzerschnittstelle/komponenten/WrapperPanel.java
  src/benutzerschnittstelle/komponenten/charts/BarChart.java
  src/benutzerschnittstelle/komponenten/charts/LineChart.java
  src/benutzerschnittstelle/management/Kategorieliste.java
  src/benutzerschnittstelle/management/Kategorieuebersicht.java
  src/benutzerschnittstelle/management/ListView.java
  src/benutzerschnittstelle/management/VokabelScreen.java
  src/benutzerschnittstelle/management/Vokabelliste.java
  src/benutzerschnittstelle/uebersicht/Kategorieliste.java
  src/benutzerschnittstelle/uebersicht/Vokabelliste.java
  src/datenspeicherung/Datenbank.java
  src/datenspeicherung/Vokabel.java
  src/exceptions/EndOfAbfrageException.java
  src/exceptions/datenbank/DatenbankAccessException.java
  src/exceptions/datenbank/DatenbankLeseException.java
  src/exceptions/datenbank/DatenbankSchreibException.java
  src/exceptions/datenbank/DuplicateVokabelException.java
  src/fachkonzept/AbfrageKonzept.java
  src/fachkonzept/ErstellerKonzept.java
  src/fachkonzept/datamangement/tablemodels/CustomTableModel.java
  src/fachkonzept/datamangement/tablemodels/KategorieTableModel.java
  src/fachkonzept/datamangement/tablemodels/VokabelTableModel.java
  src/steuerung/MainFrameSteuerung.java
  src/steuerung/management/KategorieUebersichtsSteuerung.java
  src/steuerung/management/KategorielisteSteuerung.java
  src/steuerung/management/ListenSteuerung.java
  src/steuerung/management/VokabelScreenSteuerung.java
  src/steuerung/management/VokabellisteSteuerung.java
  src/steuerung/uebersicht/KategorieUebersichtsSteuerung.java
  src/steuerung/uebersicht/KategorielisteSteuerung.java
  src/steuerung/uebersicht/VokabellisteSteuerung.java
Labels: enhancement, frontend, backend, project

#37 Navigation Stack
  Tests/datenbank/DatenbankVokabelTest.java
  src/benutzerschnittstelle/MainFrame.java
  src/benutzerschnittstelle/komponenten/WrapperPanel.java
  src/benutzerschnittstelle/navigation/NavigationBar.java
  src/fachkonzept/navigation/NavigationStack.java
  src/fachkonzept/navigation/NavigationStackItem.java
  src/steuerung/MainFrameSteuerung.java
Labels: backend, feature
